/*
 * generated by Xtext
 */
package org.xtext.com;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class JavadslRuntimeModule extends org.xtext.com.AbstractJavadslRuntimeModule {

}
