/*
 * generated by Xtext
 */
package org.xtext.com.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

import org.xtext.com.ui.internal.JavadslActivator;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class JavadslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return JavadslActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return JavadslActivator.getInstance().getInjector(JavadslActivator.ORG_XTEXT_COM_JAVADSL);
	}
	
}
