/*
 * generated by Xtext
 */
package org.xtext.com;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class JavadslUiInjectorProvider implements IInjectorProvider {
	
	@Override
	public Injector getInjector() {
		return org.xtext.com.ui.internal.JavadslActivator.getInstance().getInjector("org.xtext.com.Javadsl");
	}
	
}
