/*
 * generated by Xtext
 */
package org.xtext.com.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class JavadslUiModule extends org.xtext.com.ui.AbstractJavadslUiModule {
	public JavadslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
